## 2.3

### Exercise

#### Q6

In [1]:
import torch

A = torch.arange(6).reshape(3, 2)
# A / A.sum(axis=1)  # will be error, should add keepdims=True 
A / A.sum(axis=1, keepdim=True)  # find that it is normalization for row

tensor([[0.0000, 1.0000],
        [0.4000, 0.6000],
        [0.4444, 0.5556]])

#### Q10

In [5]:
A = torch.randn(1<<10, 1<<16)
B = torch.randn(1<<16, 1<<5)
C = torch.randn(1<<5, 1<<14)

In [ ]:
A @ (B @ C)  # 2^35 + 2^40 (Fun fact: runtime 3.7s in cpu, much faster than I had imagined.)

tensor([[-1052.2369,  -173.7053,  2186.3254,  ..., -1784.6118,  -418.7856,
          2909.9258],
        [-2257.2368,  3383.9558,  5186.9253,  ...,  2860.7244,  1445.2439,
         -2483.0007],
        [ 1181.4535,  -299.5946, -2176.8145,  ...,   679.2690,   143.7754,
          2203.1426],
        ...,
        [-3919.2593,  -273.7480,   632.2150,  ...,   243.1515,  1573.8942,
          1463.7803],
        [ 1551.0665, -2127.3672,    55.8942,  ...,   112.1325,   -84.8309,
           650.4166],
        [ 1426.0148,   118.7593,  2294.7441,  ...,  3022.2122,   845.0978,
            95.6036]])

In [ ]:
(A @ B) @ C  # 2^31 + 2^29

tensor([[-1052.2361,  -173.7055,  2186.3259,  ..., -1784.6124,  -418.7862,
          2909.9268],
        [-2257.2363,  3383.9565,  5186.9229,  ...,  2860.7236,  1445.2421,
         -2483.0007],
        [ 1181.4547,  -299.5953, -2176.8152,  ...,   679.2677,   143.7762,
          2203.1431],
        ...,
        [-3919.2583,  -273.7475,   632.2156,  ...,   243.1524,  1573.8943,
          1463.7799],
        [ 1551.0670, -2127.3660,    55.8944,  ...,   112.1328,   -84.8322,
           650.4165],
        [ 1426.0151,   118.7586,  2294.7451,  ...,  3022.2136,   845.0985,
            95.6024]])

#### Q12

In [10]:
A = torch.randn(100, 200)
B = torch.randn(100, 200)
C = torch.randn(100, 200)
D = torch.stack([A, B, C], dim=2)
assert torch.allclose(D[:, :, 1], B)